#!/usr/bin/env bash
# Assemble the modular web sources into ONE self-contained index.html, gzip it,
# and emit it as a PROGMEM C array the firmware serves.  Authoring stays modular
# (shell + css + app + one file per game); the device gets one compressed blob.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WEB="$ROOT/web"
DIST="$ROOT/dist"; mkdir -p "$DIST"
OUT="$ROOT/GamingCabinet/webassets.h"

# 1) assemble: inline style.css, app.js, and every games/*.js into shell.html markers
python3 - "$WEB" "$DIST/index.html" <<'PY'
import sys, glob, os
web, out = sys.argv[1], sys.argv[2]
shell = open(os.path.join(web, 'shell.html')).read()
css   = open(os.path.join(web, 'style.css')).read()
app   = open(os.path.join(web, 'app.js')).read()
games = ''
for f in sorted(glob.glob(os.path.join(web, 'games', '*.js'))):
    games += "\n/* ==== %s ==== */\n" % os.path.basename(f) + open(f).read() + "\n"
html = (shell.replace('/*__STYLE__*/', css)
             .replace('/*__APP__*/', app)
             .replace('/*__GAMES__*/', games))
open(out, 'w').write(html)
print("  assembled: %d bytes  (%d game files)" % (len(html), len(glob.glob(os.path.join(web,'games','*.js')))))
PY

# 2) gzip + emit PROGMEM header
python3 - "$DIST/index.html" "$OUT" <<'PY'
import sys, gzip
src, out = sys.argv[1], sys.argv[2]
raw = open(src, 'rb').read()
gz  = gzip.compress(raw, 9)
with open(out, 'w') as f:
    f.write("// generated by tools/bundle.sh -- DO NOT EDIT\n#pragma once\n")
    f.write("const unsigned int WEB_HTML_GZ_LEN = %d;   // uncompressed: %d\n" % (len(gz), len(raw)))
    f.write("const unsigned char WEB_HTML_GZ[] PROGMEM = {\n")
    f.write(",".join(str(b) for b in gz))
    f.write("\n};\n")
print("  gzipped:   %d -> %d bytes (%.1f%%)  -> %s" % (len(raw), len(gz), 100*len(gz)/max(1,len(raw)), out))
PY
echo "bundle done."
